name: actions output test
on: workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: output test
        id: key
        run: echo "VAR=action output" >> $GITHUB_OUTPUT

      - name: output check
        run: echo ${{ steps.key.outputs.VAR }}
          
  check:
    runs-on: ubuntu-latest
    needs: job

    steps:
      - name: output check in other job
        run: echo ${{ needs.job.key.outputs.call }}
