name: actions output test
on: workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest

    outputs:
      VAR: ${{ steps.key.outputs.VAR }}

    steps:
      - name: output test
        id: key
        run: echo "VAR=action output" >> $GITHUB_OUTPUT

  check:
    runs-on: ubuntu-latest
    needs: job

    steps:
      - name: output check in other job
        run: echo ${{ needs.job.outputs.VAR }}
