name: matrix test
on: workflow_dispatch
jobs:
  matrix_test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: test steps
        run: echo Hello World in ${{ matrix.os }}
